MAINFILE := ./jasdm.tex

all:
	latex $(MAINFILE)
	latex $(MAINFILE)
	latex $(MAINFILE)
	pdflatex $(MAINFILE)

clean:
	@rm *.log *.lof *.toc *.nav *.snm *.out *.dvi *.aux *.backup */*.backup */*.aux 2>/dev/null
